sudo: false

language: python

python:
  - "3.7"
  - "3.8"

env:
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<3.0.0"
  - DJANGO="Django>=3.0.4,<3.0.5"

install:
  - pip install $DJANGO -e .[tests]
  - pip freeze

script:
  - pytest
